#!/bin/sh
set -ue

TAG="cpu-mon"

TOP_WIDTH_MAX=512

REFRESH_RATE=${REFRESH_RATE:-5s}
PROCESS_COUNT=${PROCESS_COUNT:-10}

while true ; do
	top -n1 -b -c -w "$TOP_WIDTH_MAX" |
        grep -F -A "$PROCESS_COUNT" 'PID USER' |
        grep -F -v 'PID USER' |
        head -n "$PROCESS_COUNT" |
        logger -t $TAG -e

	sleep "$REFRESH_RATE"
done
